server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: SYSTEM-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp16730aq4j29ys9y5o.mysql.rds.aliyuncs.com:3306/lgh-system?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: languohui
    password: languohui!@#$%^*()
    druid:
      #Spring Boot 默认是不注入这些属性值的，需要自己绑定
      #druid 数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

      #配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #IP白名单（不配置默认允许所有访问）
        allow: 127.0.0.1,192.168.0.82
        #IP黑名单
        #deny: 192.168.0.81
        reset-enable: false
        #登录名
        login-username: admin
        #登录密码
        login-password: 123456
mybatis-plus:
  mapper-locations: classpath*:com/languohui/lgh/mapper/*Mapper.xml
  type-aliases-package: com.languohui.lgh.domain,com.languohui.lgh.query
#日志
logging:
  level:
    com.languohui.lgh: debug
